# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        go-version: ['1.21']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2